---
# tasks file for nginx
- name: install nginx
  yum: name=nginx state=present

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes 

- name: creates directory
  file: path=/etc/nginx/conf.d state=directory

- name: copy nginx conf
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: copy nginx conf wordpress
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx
