---
# tasks file for mysql
- name: install mysql 
  yum: name={{ item }} state=present 
  with_items:
    - mysql
    - 

- name: Configure Selinux
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: ansible_selinux.status == "enabled"

- name: Create mysql conf
  template: src=my.cnf.j2 dest=/etc/my.cnf 
  notify: 
    - restart mysql

- name: start mysql
  notify: start mysql 
