---
# tasks file for mysql
- name: install mysql 
  yum: 
    name: ['mariadb.x86_64', 'mariadb-server', 'MySQL-python', 'libselinux-python', 'libsemanage-python'] 
    state: present 

- name: Configure Selinux
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: ansible_selinux.status == "enabled"

- name: Start MariaDb
  service:
    name: mariadb
    state: started 
    enabled: yes

- name: Create mysql conf
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: restart mariadb  

- name: Create WordPress database
  mysql_db: name={{ wp_db_name }} state=present

- name: Create WordPress database user
  mysql_user: 
    name: '{{ wp_db_user }}'
    password: '{{ wp_db_password }}'
    priv: '{{ wp_db_name }}.*:ALL'
    host: 'localhost'
    state: present
  notify: restart mariadb
