---
# tasks file for mysql
- name: install mysql 
  yum: name={{ item }} state=present 
  with_items:
    - mariadb.x86_64
    - mariadb-server
    - MySQL-python
    - libselinux-python
    - libsemanage-python

- name: Configure Selinux
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: ansible_selinux.status == "enabled"

- name: Create mysql conf
  template: src=my.cnf.j2 dest=/etc/my.cnf 

- nome: Create WordPress database
  mysql_db: name={{ wp_db_name }} state=present

- name: Create WordPress database user
  mysql_user: 
    name: '{{ wp_db_user }}'
    password: '{{ wp_db_password }}'
    priv: '{{ wp_db_name }}.*:ALL'
    host: '{{ ansible_default_ipv4.address }}'
    state: present
  notify: restart mariadb
