---
# tasks file for common
- name: install common packages
  yum: name={{ item }} state=present
  with_items:
    - epel-release
    - libselinux-python
    - MySQL-python.x86_64

- name: Reload ansible-facts
  setup: 
